FROM node:14-buster-slim As Stage1

# Load all the environment variables
ARG ENV_VARIABLES

ENV NODE_ENV=production \
    PROJECT_HOME=/usr/app/ \
    DEBUG="app:*" \
    BUILD_DEPS="git python openssh-server build-essential"

# install deps
RUN apt-get update > /dev/null \
    && apt-get install -y -qq --no-install-recommends ${BUILD_DEPS} ca-certificates \
    vim curl > /dev/null

# create project home
RUN mkdir -p ${PROJECT_HOME}

# switch to working directory
WORKDIR ${PROJECT_HOME}

# For all the items in the build argument create a custom .env file
#RUN IFS=';'; \
#    for item in $ENV_VARIABLES; do \
#    echo $item >> "${PROJECT_HOME}/.env"; \
#    done;

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ${PROJECT_HOME}

#npm install
RUN npm i -g npm@6 \
    && npm install --quiet

#cleanup
RUN apt-get purge -y ${BUILD_DEPS} > /dev/null \
    && rm -rf /var/lib/apt/lists/*

# copy source code and run the build
COPY . $PROJECT_HOME

# Exporting to the environment before build rather than using .env file
RUN IFS=';'; \
    for item in $ENV_VARIABLES; do \
#    echo $item; \
    export $item; \
    done \
    && npm run build

#RUN npm run build

#Stage 2
#######################################
FROM node:14-buster-slim

ENV NODE_ENV=production \
    PROJECT_HOME=/usr/app/ \
    DEBUG="app:*"

# install deps
RUN apt-get update > /dev/null \
    && apt-get install -y -qq --no-install-recommends ${BUILD_DEPS} ca-certificates \
    vim curl > /dev/null

# create project home
RUN mkdir -p ${PROJECT_HOME}

# Set working directory to nginx resources directory
WORKDIR $PROJECT_HOME

# Copies npm related resources
COPY --from=Stage1 $PROJECT_HOME/node_modules $PROJECT_HOME/node_modules
COPY --from=Stage1 $PROJECT_HOME/package.json $PROJECT_HOME/

# Copies static resources from builder stage
COPY --from=Stage1 $PROJECT_HOME/.next/ $PROJECT_HOME/.next

# Copies pm2 related resources
COPY --from=Stage1 $PROJECT_HOME/process.yml $PROJECT_HOME/

#npm install
RUN npm i -g npm@6 \
    && npm i -g --quiet pm2

#cleanup
RUN apt-get purge -y ${BUILD_DEPS} > /dev/null \
    && rm -rf /var/lib/apt/lists/*


EXPOSE 80 443 8080

# start the application
CMD ["pm2","start","process.yml","--attach"]

