/** @type {import('next').NextConfig} */

const { i18n } = require("./next-i18next.config");
const securityHeaders = [];

if (process.env.NEXT_PUBLIC_NODE_ENV === "production") {
  // const CLOUDFRONT_URL = process.env.NEXT_PUBLIC_CLOUDFRONT_URL;
  // const S3_BUCKET_URL_STATIC = process.env.NEXT_PUBLIC_S3_BUCKET_STATIC_URL;
  let allowDomains = "https://apisandbox.demo.com".split("||");
  let connectSrcDomains = [
    "'self'",

    /**
     * Chart Js related
     */
    "https://*.unpkg.com:*",
    "https://unpkg.com",
    /****/

    "https://*.facebook.com",
    "https://*.facebook.net",
    "https://*.google.com",
    "https://*.google.ad",
    "https://*.google.ae",
    "https://*.google.com.af",
    "https://*.google.com.ag",
    "https://*.google.com.ai",
    "https://*.google.al",
    "https://*.google.am",
    "https://*.google.co.ao",
    "https://*.google.com.ar",
    "https://*.google.as",
    "https://*.google.at",
    "https://*.google.com.au",
    "https://*.google.az",
    "https://*.google.ba",
    "https://*.google.com.bd",
    "https://*.google.be",
    "https://*.google.bf",
    "https://*.google.bg",
    "https://*.google.com.bh",
    "https://*.google.bi",
    "https://*.google.bj",
    "https://*.google.com.bn",
    "https://*.google.com.bo",
    "https://*.google.com.br",
    "https://*.google.bs",
    "https://*.google.bt",
    "https://*.google.co.bw",
    "https://*.google.by",
    "https://*.google.com.bz",
    "https://*.google.ca",
    "https://*.google.cd",
    "https://*.google.cf",
    "https://*.google.cg",
    "https://*.google.ch",
    "https://*.google.ci",
    "https://*.google.co.ck",
    "https://*.google.cl",
    "https://*.google.cm",
    "https://*.google.cn",
    "https://*.google.com.co",
    "https://*.google.co.cr",
    "https://*.google.com.cu",
    "https://*.google.cv",
    "https://*.google.com.cy",
    "https://*.google.cz",
    "https://*.google.de",
    "https://*.google.dj",
    "https://*.google.dk",
    "https://*.google.dm",
    "https://*.google.com.do",
    "https://*.google.dz",
    "https://*.google.com.ec",
    "https://*.google.ee",
    "https://*.google.com.eg",
    "https://*.google.es",
    "https://*.google.com.et",
    "https://*.google.fi",
    "https://*.google.com.fj",
    "https://*.google.fm",
    "https://*.google.fr",
    "https://*.google.ga",
    "https://*.google.ge",
    "https://*.google.gg",
    "https://*.google.com.gh",
    "https://*.google.com.gi",
    "https://*.google.gl",
    "https://*.google.gm",
    "https://*.google.gr",
    "https://*.google.com.gt",
    "https://*.google.gy",
    "https://*.google.com.hk",
    "https://*.google.hn",
    "https://*.google.hr",
    "https://*.google.ht",
    "https://*.google.hu",
    "https://*.google.co.id",
    "https://*.google.ie",
    "https://*.google.co.il",
    "https://*.google.im",
    "https://*.google.co.in",
    "https://*.google.iq",
    "https://*.google.is",
    "https://*.google.it",
    "https://*.google.je",
    "https://*.google.com.jm",
    "https://*.google.jo",
    "https://*.google.co.jp",
    "https://*.google.co.ke",
    "https://*.google.com.kh",
    "https://*.google.ki",
    "https://*.google.kg",
    "https://*.google.co.kr",
    "https://*.google.com.kw",
    "https://*.google.kz",
    "https://*.google.la",
    "https://*.google.com.lb",
    "https://*.google.li",
    "https://*.google.lk",
    "https://*.google.co.ls",
    "https://*.google.lt",
    "https://*.google.lu",
    "https://*.google.lv",
    "https://*.google.com.ly",
    "https://*.google.co.ma",
    "https://*.google.md",
    "https://*.google.me",
    "https://*.google.mg",
    "https://*.google.mk",
    "https://*.google.ml",
    "https://*.google.com.mm",
    "https://*.google.mn",
    "https://*.google.ms",
    "https://*.google.com.mt",
    "https://*.google.mu",
    "https://*.google.mv",
    "https://*.google.mw",
    "https://*.google.com.mx",
    "https://*.google.com.my",
    "https://*.google.co.mz",
    "https://*.google.com.na",
    "https://*.google.com.ng",
    "https://*.google.com.ni",
    "https://*.google.ne",
    "https://*.google.nl",
    "https://*.google.no",
    "https://*.google.com.np",
    "https://*.google.nr",
    "https://*.google.nu",
    "https://*.google.co.nz",
    "https://*.google.com.om",
    "https://*.google.com.pa",
    "https://*.google.com.pe",
    "https://*.google.com.pg",
    "https://*.google.com.ph",
    "https://*.google.com.pk",
    "https://*.google.pl",
    "https://*.google.pn",
    "https://*.google.com.pr",
    "https://*.google.ps",
    "https://*.google.pt",
    "https://*.google.com.py",
    "https://*.google.com.qa",
    "https://*.google.ro",
    "https://*.google.ru",
    "https://*.google.rw",
    "https://*.google.com.sa",
    "https://*.google.com.sb",
    "https://*.google.sc",
    "https://*.google.se",
    "https://*.google.com.sg",
    "https://*.google.sh",
    "https://*.google.si",
    "https://*.google.sk",
    "https://*.google.com.sl",
    "https://*.google.sn",
    "https://*.google.so",
    "https://*.google.sm",
    "https://*.google.sr",
    "https://*.google.st",
    "https://*.google.com.sv",
    "https://*.google.td",
    "https://*.google.tg",
    "https://*.google.co.th",
    "https://*.google.com.tj",
    "https://*.google.tl",
    "https://*.google.tm",
    "https://*.google.tn",
    "https://*.google.to",
    "https://*.google.com.tr",
    "https://*.google.tt",
    "https://*.google.com.tw",
    "https://*.google.co.tz",
    "https://*.google.com.ua",
    "https://*.google.co.ug",
    "https://*.google.co.uk",
    "https://*.google.com.uy",
    "https://*.google.co.uz",
    "https://*.google.com.vc",
    "https://*.google.co.ve",
    "https://*.google.vg",
    "https://*.google.co.vi",
    "https://*.google.com.vn",
    "https://*.google.vu",
    "https://*.google.ws",
    "https://*.google.rs",
    "https://*.google.co.za",
    "https://*.google.co.zm",
    "https://*.google.co.zw",
    "https://*.google.cat",

    /****/
    CLOUDFRONT_URL,
    S3_BUCKET_URL_STATIC,
    ...allowDomains,
  ];

  /**
   * QA only configurations
   */
  if (process.env.NEXT_PUBLIC_WEB_ENV === "qa") {
    connectSrcDomains = [
      ...connectSrcDomains,
      "https://*.demo.com",
      "https://*.google-analytics.com",
      "https://*.google.com",
    ];
  }

  /**
   * PROD only configuration
   */
  if (process.env.NEXT_PUBLIC_WEB_ENV === "production") {
    connectSrcDomains = [
      ...connectSrcDomains,
      "https://www.google-analytics.com",
      "https://*.demo.com",
    ];
  }

  const directives = {
    defaultSrc: ["'self'"],
    scriptSrc: [
      "'self'",
      "blob:",
      "https://geoip-db.com",
      "https://www.googletagmanager.com",
      "https://ajax.googleapis.com",
      "https://www.youtube.com",
      "https://www.google-analytics.com",

      "https://*.demo.com",

      /**
       * Chart Js related
       */
      "https://*.unpkg.com:*",
      "https://unpkg.com",
      /****/
    ],
    styleSrc: [
      "'self'",
      "https://*.demo.com",
      "https://fonts.googleapis.com",
      "https://fonts.cdnfonts.com",
      "https://pro.fontawesome.com",
      "https://use.typekit.net",
      "https://p.typekit.net",
      "https://www.gstatic.com",
    ],
    imgSrc: [
      "'self'",
      "blob:",
      "data:",

      "https://*.facebook.com",
      "https://*.google-analytics.com",
      "https://*.google.com",
      "https://*.google.co.in",
      "https://*.akamaihd.net",
      "https://*.razorpay.com",

      "https://*.google.com",
      "https://*.google.ad",
      "https://*.google.ae",
      "https://*.google.com.af",
      "https://*.google.com.ag",
      "https://*.google.com.ai",
      "https://*.google.al",
      "https://*.google.am",
      "https://*.google.co.ao",
      "https://*.google.com.ar",
      "https://*.google.as",
      "https://*.google.at",
      "https://*.google.com.au",
      "https://*.google.az",
      "https://*.google.ba",
      "https://*.google.com.bd",
      "https://*.google.be",
      "https://*.google.bf",
      "https://*.google.bg",
      "https://*.google.com.bh",
      "https://*.google.bi",
      "https://*.google.bj",
      "https://*.google.com.bn",
      "https://*.google.com.bo",
      "https://*.google.com.br",
      "https://*.google.bs",
      "https://*.google.bt",
      "https://*.google.co.bw",
      "https://*.google.by",
      "https://*.google.com.bz",
      "https://*.google.ca",
      "https://*.google.cd",
      "https://*.google.cf",
      "https://*.google.cg",
      "https://*.google.ch",
      "https://*.google.ci",
      "https://*.google.co.ck",
      "https://*.google.cl",
      "https://*.google.cm",
      "https://*.google.cn",
      "https://*.google.com.co",
      "https://*.google.co.cr",
      "https://*.google.com.cu",
      "https://*.google.cv",
      "https://*.google.com.cy",
      "https://*.google.cz",
      "https://*.google.de",
      "https://*.google.dj",
      "https://*.google.dk",
      "https://*.google.dm",
      "https://*.google.com.do",
      "https://*.google.dz",
      "https://*.google.com.ec",
      "https://*.google.ee",
      "https://*.google.com.eg",
      "https://*.google.es",
      "https://*.google.com.et",
      "https://*.google.fi",
      "https://*.google.com.fj",
      "https://*.google.fm",
      "https://*.google.fr",
      "https://*.google.ga",
      "https://*.google.ge",
      "https://*.google.gg",
      "https://*.google.com.gh",
      "https://*.google.com.gi",
      "https://*.google.gl",
      "https://*.google.gm",
      "https://*.google.gr",
      "https://*.google.com.gt",
      "https://*.google.gy",
      "https://*.google.com.hk",
      "https://*.google.hn",
      "https://*.google.hr",
      "https://*.google.ht",
      "https://*.google.hu",
      "https://*.google.co.id",
      "https://*.google.ie",
      "https://*.google.co.il",
      "https://*.google.im",
      "https://*.google.co.in",
      "https://*.google.iq",
      "https://*.google.is",
      "https://*.google.it",
      "https://*.google.je",
      "https://*.google.com.jm",
      "https://*.google.jo",
      "https://*.google.co.jp",
      "https://*.google.co.ke",
      "https://*.google.com.kh",
      "https://*.google.ki",
      "https://*.google.kg",
      "https://*.google.co.kr",
      "https://*.google.com.kw",
      "https://*.google.kz",
      "https://*.google.la",
      "https://*.google.com.lb",
      "https://*.google.li",
      "https://*.google.lk",
      "https://*.google.co.ls",
      "https://*.google.lt",
      "https://*.google.lu",
      "https://*.google.lv",
      "https://*.google.com.ly",
      "https://*.google.co.ma",
      "https://*.google.md",
      "https://*.google.me",
      "https://*.google.mg",
      "https://*.google.mk",
      "https://*.google.ml",
      "https://*.google.com.mm",
      "https://*.google.mn",
      "https://*.google.ms",
      "https://*.google.com.mt",
      "https://*.google.mu",
      "https://*.google.mv",
      "https://*.google.mw",
      "https://*.google.com.mx",
      "https://*.google.com.my",
      "https://*.google.co.mz",
      "https://*.google.com.na",
      "https://*.google.com.ng",
      "https://*.google.com.ni",
      "https://*.google.ne",
      "https://*.google.nl",
      "https://*.google.no",
      "https://*.google.com.np",
      "https://*.google.nr",
      "https://*.google.nu",
      "https://*.google.co.nz",
      "https://*.google.com.om",
      "https://*.google.com.pa",
      "https://*.google.com.pe",
      "https://*.google.com.pg",
      "https://*.google.com.ph",
      "https://*.google.com.pk",
      "https://*.google.pl",
      "https://*.google.pn",
      "https://*.google.com.pr",
      "https://*.google.ps",
      "https://*.google.pt",
      "https://*.google.com.py",
      "https://*.google.com.qa",
      "https://*.google.ro",
      "https://*.google.ru",
      "https://*.google.rw",
      "https://*.google.com.sa",
      "https://*.google.com.sb",
      "https://*.google.sc",
      "https://*.google.se",
      "https://*.google.com.sg",
      "https://*.google.sh",
      "https://*.google.si",
      "https://*.google.sk",
      "https://*.google.com.sl",
      "https://*.google.sn",
      "https://*.google.so",
      "https://*.google.sm",
      "https://*.google.sr",
      "https://*.google.st",
      "https://*.google.com.sv",
      "https://*.google.td",
      "https://*.google.tg",
      "https://*.google.co.th",
      "https://*.google.com.tj",
      "https://*.google.tl",
      "https://*.google.tm",
      "https://*.google.tn",
      "https://*.google.to",
      "https://*.google.com.tr",
      "https://*.google.tt",
      "https://*.google.com.tw",
      "https://*.google.co.tz",
      "https://*.google.com.ua",
      "https://*.google.co.ug",
      "https://*.google.co.uk",
      "https://*.google.com.uy",
      "https://*.google.co.uz",
      "https://*.google.com.vc",
      "https://*.google.co.ve",
      "https://*.google.vg",
      "https://*.google.co.vi",
      "https://*.google.com.vn",
      "https://*.google.vu",
      "https://*.google.ws",
      "https://*.google.rs",
      "https://*.google.co.za",
      "https://*.google.co.zm",
      "https://*.google.co.zw",
      "https://*.google.cat",
      "https://*.demo.com",
    ],
    connectSrc: connectSrcDomains,
    fontSrc: [
      "'self'",
      "blob:",
      "data:",
      "https://*.demo.com",
      "https://fonts.gstatic.com",
      "https://fonts.cdnfonts.com",
      "https://pro.fontawesome.com",
      "https://use.typekit.net",
      "https://p.typekit.net",
      "https://www.gstatic.com",
      "https://c1.sfdcstatic.com",

      "https://*.force.com",
    ],
    objectSrc: ["'self'"],
    mediaSrc: [
      "'self'",
      "blob:",
      "data:",

      "https://*.wistia.com",
      "https://*.wistia.net",
      "https://*.kaltura.com",
      "https://*.demo.com",

      "https://*.force.com",

      /**
       * Chart Js related
       */
      "https://*.unpkg.com:*",
      "https://unpkg.com",
      /****/
    ],
    frameSrc: [
      "'self'",
      "https://*.google.com",
      "https://www.youtube.com",
      "https://*.wistia.com",
      "https://*.wistia.net",
      "https://*.facebook.com",
      "https://*.zoho.com",
      "https://*.zoho.in",
      "https://*.demo.com",
    ],
  };

  if (
    process.env.NEXT_PUBLIC_WEB_ENV === "dev" ||
    process.env.NEXT_PUBLIC_WEB_ENV === "qa" ||
    process.env.NEXT_PUBLIC_WEB_ENV === "production"
  ) {
    directives.styleSrc.push(...["'unsafe-inline'", "'unsafe-eval'"]);
    directives.scriptSrc.push(...["'unsafe-inline'", "'unsafe-eval'"]);
  }

  const ContentSecurityPolicy = `
  default-src ${directives.defaultSrc.join(",")};
  script-src ${directives.scriptSrc.join(",")}; 
  style-src ${directives.styleSrc.join(",")};
  img-src ${directives.imgSrc.join(",")};
  font-src ${directives.fontSrc.join(",")};
  object-src ${directives.objectSrc.join(",")};
  connect-src ${directives.connectSrc.join(",")};
  media-src ${directives.mediaSrc.join(",")};
  frame-src ${directives.frameSrc.join(",")};
`;
  const headers = [
    {
      key: "X-XSS-Protection",
      value: "0",
    },
    {
      key: "Referrer-Policy",
      value: "strict-origin-when-cross-origin",
    },
    /*{
      key: 'X-Content-Type-Options',
      value: 'nosniff'
    },*/

    {
      key: "Strict-Transport-Security",
      value: "max-age=31536000; preload",
    },
    {
      key: "Content-Security-Policy",
      value: ContentSecurityPolicy.replace(/\s{2,}|,/g, " ").trim(),
    },
  ];

  securityHeaders.push({
    // Apply these headers to all routes in your application.
    source: "/:path*",
    headers: headers,
  });
}
const moduleExports = {
  async headers() {
    return [...securityHeaders];
  },
  // app.disable('x-powered-by');
  poweredByHeader: false,
  i18n,
  reactStrictMode: true,

  images: {
    domains: [
      "demo-dev.s3.amazonaws.com",
      "apisandbox.demo.com",
      "commondatastorage.googleapis.com",
      "demo-demo.s3.amazonaws.com",
    ],
  },
  productionBrowserSourceMaps: true,
};

module.exports = moduleExports;
