export const API_ENDPOINT = process.env.NEXT_PUBLIC_API_ENDPOINT;
export const API_ENDPOINT_PHP = process.env.NEXT_PUBLIC_API_ENDPOINT_PHP;
export const PATH_ACCOUNT = "/account";
export const PATH_PARTNER = "/partner";
export const PATH_SUBSCRIPTION = "/subscription";
export const PATH_CONTENT = "/content";

export const ENDPOINT_GET_USER_TOKEN = "/getusertoken";
export const GET_REFRESH_TOKEN_URL = "/gettokenbyrefreshtoken";

export const ENDPOINT_ADD_RESELLER = PATH_PARTNER + "/user/reseller";
export const ADD_RESELLER_SUCCESS = "ADD_RESELLER_SUCCESS";
export const ADD_RESELLER_ERROR = "ADD_RESELLER_ERROR";
export const RESET_ADD_RESELLER = "RESET_ADD_RESELLER";

export const ENDPOINT_GLOBAL_COUNTRY = PATH_PARTNER + "/global/country";
export const GLOBAL_COUNTRY_SUCCESS = "GLOBAL_COUNTRY_SUCCESS";
export const GLOBAL_COUNTRY_ERROR = "GLOBAL_COUNTRY_ERROR";

export const ENDPOINT_GLOBAL_DISTRICT = PATH_PARTNER + "/global/district";
export const GLOBAL_DISTRICT_SUCCESS = "GLOBAL_DISTRICT_SUCCESS";
export const GLOBAL_DISTRICT_ERROR = "GLOBAL_DISTRICT_ERROR";

export const ENDPOINT_ADD_PARTNER = PATH_ACCOUNT + "/auth/partner";
export const ADD_PARTNER_SUCCESS = "ADD_PARTNER_SUCCESS";
export const ADD_PARTNER_ERROR = "ADD_PARTNER_ERROR";

export const ENDPOINT_GET_RESELLER = PATH_PARTNER + "/user/reseller";
export const GET_RESELLER_SUCCESS = "GET_RESELLER_SUCCESS";
export const GET_RESELLER_ERROR = "GET_RESELLER_ERROR";

export const ENDPOINT_GET_RESELLER_BY_USER_ID = PATH_PARTNER + "/user/reseller";
export const GET_RESELLER_BY_USER_ID_SUCCESS =
  "GET_RESELLER_BY_USER_ID_SUCCESS";
export const GET_RESELLER_BY_USER_ID_ERROR = "GET_RESELLER_BY_USER_ID_ERROR";

export const ENDPOINT_GET_USER_INFO = "/getuserinfo";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_ERROR = "GET_USER_INFO_ERROR";

export const ENDPOINT_GET_ORGANIZATION = PATH_PARTNER + "/user/school";
export const GET_ORGANIZATION_SUCCESS = "GET_ORGANIZATION_SUCCESS";
export const GET_ORGANIZATION_ERROR = "GET_ORGANIZATION_ERROR";

export const ENDPOINT_GET_ORGANIZATION_BY_RESELLER_ID =
  PATH_PARTNER + "/user/school";
export const GET_ORGANIZATION_BY_RESELLER_ID_SUCCESS =
  "GET_ORGANIZATION_BY_RESELLER_ID_SUCCESS";
export const GET_ORGANIZATION_BY_RESELLER_ID_ERROR =
  "GET_ORGANIZATION_BY_RESELLER_ID_ERROR";

export const ENDPOINT_ADD_ORGANIZATION = PATH_PARTNER + "/user/school";
export const ADD_ORGANIZATION_SUCCESS = "ADD_ORGANIZATION_SUCCESS";
export const ADD_ORGANIZATION_ERROR = "ADD_ORGANIZATION_ERROR";
export const RESET_ADD_ORGANIZATION = "RESET_ADD_ORGANIZATION";

export const ENDPOINT_ADD_UPLOAD_ORGANIZATION_DOC =
  PATH_PARTNER + "/user/school-agreement";
export const ADD_UPLOAD_ORGANIZATION_DOC_SUCCESS =
  "ADD_UPLOAD_ORGANIZATION_DOC_SUCCESS";
export const ADD_UPLOAD_ORGANIZATION_DOC_ERROR =
  "ADD_UPLOAD_ORGANIZATION_DOC_ERROR";

export const ENDPOINT_GET_ORGANIZATION_DETAIL = PATH_PARTNER + "/user/school";
export const GET_ORGANIZATION_DETAIL_SUCCESS =
  "GET_ORGANIZATION_DETAIL_SUCCESS";
export const GET_ORGANIZATION_DETAIL_ERROR = "GET_ORGANIZATION_DETAIL_ERROR";

export const ENDPOINT_GET_SKU_LISTING = PATH_PARTNER + "/global/sku";
export const GET_SKU_LISTING_SUCCESS = "GET_SKU_LISTING_SUCCESS";
export const GET_SKU_LISTING_ERROR = "GET_SKU_LISTING_ERROR";

export const ENDPOINT_GET_SKU_DESCRIPTION = PATH_PARTNER + "/global/sku";
export const GET_SKU_DESCRIPTION_SUCCESS = "GET_SKU_DESCRIPTION_SUCCESS";
export const GET_SKU_DESCRIPTION_ERROR = "GET_SKU_DESCRIPTION_ERROR";
export const RESET_SKU_DESCRIPTION = "RESET_SKU_DESCRIPTION";

export const ENDPOINT_ADD_LICENSE = PATH_PARTNER + "/user/school-license";
export const ADD_LICENSE_SUCCESS = "ADD_LICENSE_SUCCESS";
export const ADD_LICENSE_ERROR = "ADD_LICENSE_ERROR";
export const RESET_ADD_LICENSE = "RESET_ADD_LICENSE";

export const ENDPOINT_GET_SCHOOL_LICENSE =
  PATH_PARTNER + "/user/school-license";
export const GET_SCHOOL_LICENSE_SUCCESS = "GET_SCHOOL_LICENSE_SUCCESS";
export const GET_SCHOOL_LICENSE_ERROR = "GET_SCHOOL_LICENSE_ERROR";

export const ENDPOINT_UPDATE_USER_DETAILS = "/updateprofile";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_ERROR = "UPDATE_USER_DETAILS_ERROR";

export const ENDPOINT_CHANGE_PASSWORD = "/changepassword";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
export const RESET_CHANGE_PASSWORD = "RESET_CHANGE_PASSWORD";

export const ENDPOINT_FORGOT_PASSWORD = "/forgotpassword";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_FORGOT_PASSWORD = "RESET_FORGOT_PASSWORD";

export const ENDPOINT_GET_ORDERS_LISTING = PATH_PARTNER + "/user/school-order";
export const GET_ORDERS_LISTING_SUCCESS = "GET_ORDERS_LISTING_SUCCESS";
export const GET_ORDERS_LISTING_ERROR = "GET_OORDERS_LISTING_ERROR";

export const ENDPOINT_GET_ORDER_BY_ID = PATH_PARTNER + "/user/school-order";
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS";
export const GET_ORDER_BY_ID_ERROR = "GET_ORDER_BY_ID_ERROR";

export const ENDPOINT_CREATE_ORDER = PATH_PARTNER + "/user/school-order";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";
export const RESET_CREATE_ORDER = "RESET_CREATE_ORDER";

export const APPROVED_ORDER_POST = PATH_PARTNER + "/user/finance-approval";
export const APPROVED_ORDER_SUCCESS = "APPROVED_ORDER_SUCCESS";
export const APPROVED_ORDER_ERROR = "APPROVED_ORDER_ERROR";


export const ENDPOINT_SCHOOL_ADMIN_LISTING =
  PATH_PARTNER + "/user/school-admin";
export const SCHOOL_ADMIN_LISTING_SUCCESS = "SCHOOL_ADMIN_LISTING_SUCCESS";
export const SCHOOL_ADMIN_LISTING_ERROR = "SCHOOL_ADMIN_LISTING_ERROR";

export const ENDPOINT_SET_PASSWORD = "/setpassword";
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_ERROR = "SET_PASSWORD_ERROR";

export const ENDPOINT_UPLOAD_IMAGE = "/uploadImage";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_ERROR = "UPLOAD_IMAGE_ERROR";

export const ENDPOINT_REMOVE_IMAGE = "/deleteImage";
export const REMOVE_IMAGE_SUCCESS = "REMOVE_IMAGE_SUCCESS";
export const REMOVE_IMAGE_ERROR = "REMOVE_IMAGE_ERROR";

export const ENDPOINT_LOGISTIC_DASHBOARD = PATH_PARTNER + "/dashboard/logistic";
export const LOGISTIC_DASHBOARD_SUCCESS = "LOGISTIC_DASHBOARD_SUCCESS";
export const LOGISTIC_DASHBOARD_ERROR = "LOGISTIC_DASHBOARD_ERROR";

export const ENDPOINT_RESELLER_DASHBOARD = PATH_PARTNER + "/dashboard/reseller";
export const RESELLER_DASHBOARD_SUCCESS = "RESELLER_DASHBOARD_SUCCESS";
export const RESELLER_DASHBOARD_ERROR = "RESELLER_DASHBOARD_ERROR";

export const ENDPOINT_GET_ORDER_DETAIL = PATH_PARTNER + "/user/school-order";
export const GET_ORDER_DETAIL_SUCCESS = "GET_ORDER_DETAIL_SUCCESS";
export const GET_ORDER_DETAIL_ERROR = "GET_ORDER_DETAIL_ERROR";

export const ENDPOINT_ADD_ADMIN_USER = "/addAdminUser";
export const ADD_ADMIN_USER_SUCCESS = "ADD_ADMIN_USER_SUCCESS";
export const ADD_ADMIN_USER_ERROR = "ADD_ADMIN_USER_ERROR";
export const RESET_ADD_ADMIN = "RESET_ADD_ADMIN";

export const ENDPOINT_DELETE_ADMIN_USER = "/deleteadmin'";
export const DELETE_ADMIN_USER_SUCCESS = "DELETE_ADMIN_USER_SUCCESS";
export const DELETE_ADMIN_USER_ERROR = "DELETE_ADMIN_USER_ERROR";
export const RESET_DELETE_ADMIN = "RESET_DELETE_ADMIN";

export const ENDPOINT_RESET_SCHOOL_PIN =
  PATH_PARTNER + "/user/reset-school-pin";
export const RESET_SCHOOL_PIN_SUCCESS = "RESET_SCHOOL_PIN_SUCCESS";
export const RESET_SCHOOL_PIN_ERROR = "RESET_SCHOOL_PIN_ERROR";

export const ENDPOINT_GET_SCHOOL_DEVICE_LISTING =
  PATH_PARTNER + "/user/school-device";
export const GET_SCHOOL_DEVICE_LISTING_SUCCESS =
  "GET_SCHOOL_DEVICE_LISTING_SUCCESS";
export const GET_SCHOOL_DEVICE_LISTING_ERROR =
  "GET_SCHOOL_DEVICE_LISTING_ERROR";

// Constants for cookies and storage
export const AUTHORIZATION_REFRESH_TOKEN = "refreshToken";
export const AUTHORIZATION_ID_TOKEN = "idToken";
export const AUTHORIZATION_USERNAME = "username";
export const IS_USER_LOGGED_IN = "isUserLoggedIn";
export const AUTHORIZATION_SESSION = "session";
export const USER_TYPE = "userType";
export const REMEMBER_ME = "rememberMe";
export const USER_PROFILE_PHOTO = "userProfilePhoto";
export const ENCRYPTED_USERNAME = "encryptedUsername";
export const ENCRYPTED_PASSWORD = "encryptedPassword";

// Eligible Users
export const USER_LOGISTIC = "LOGISTIC";
export const USER_RESELLER = "RESELLER";
export const USER_FINANCE = "FINANCE-TEAM";
export const USER_LOGISTIC_MANAGER = "LOGISTIC-MANAGER";
export const USER_UTID = "userUtId";
export const USER_FULL_NAME = "userFullName";
export const USER_SID = "userSid";
export const RESELLER_ID = "resellerId";

export const PATH_LOGISTIC_DASHBOARD = "/auth/logistic/dashboard";
export const PATH_RESELLER_DASHBOARD = "/auth/reseller/dashboard";
export const PATH_FINACE_ORDER = "/auth/finance/order";
